application: nico-rank
version: 2
runtime: python
api_version: 1

handlers:
- url: /report
  script: nico_rank.py
  login: admin
- url: /test
  script: test_nico_rank.py
  login: admin
- url: /.*
  script: nico_rank.py
